# Generated by Django 4.2.7 on 2023-11-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(default='', max_length=500)),
                ('time', models.TimeField(auto_now=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('poster', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
