# Generated by Django 4.2.5 on 2023-12-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningApp', '0008_alter_userprofile_rolelist_userprofilelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileLog',
        ),

        
    ]
