# Generated by Django 4.2.5 on 2023-12-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactionhistory',
            name='interaction_type',
            field=models.CharField(choices=[('upload', 'Upload'), ('read', 'Read'), ('download', 'Download')], max_length=10),
        ),
    ]
