# Generated by Django 4.2.5 on 2023-10-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_receipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='recipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
