# Generated by Django 4.2.7 on 2023-11-17 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearningApp', '0002_assignment_course_material_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='interactionhistory',
            name='material',
        ),
        migrations.RemoveField(
            model_name='interactionhistory',
            name='student',
        ),
        migrations.RemoveField(
            model_name='material',
            name='course',
        ),
        migrations.RemoveField(
            model_name='readingstate',
            name='material',
        ),
        migrations.RemoveField(
            model_name='readingstate',
            name='student',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='student',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='InteractionHistory',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='ReadingState',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
