# Generated by Django 4.2.5 on 2023-12-06 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearningApp', '0007_alter_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='roleList',
            field=models.CharField(choices=[('Student', 'Student'), ('Tutor', 'Tutor')], default='Student', max_length=15),
        ),
        migrations.CreateModel(
            name='UserProfileLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearningApp.UserProfile')),

            ],
        ),
    ]
