# Generated by Django 4.2.7 on 2023-11-19 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearningApp', '0005_userprofile_delete_customuser'),
        ('courseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearningApp.userprofile'),
        ),
    ]
