# Generated by Django 4.2.5 on 2023-11-22 20:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0002_alter_course_tutor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EnrollementApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
    ]
